version: 2.1

commands:
  setup_sbt:
    description: "Set up SBT"
    parameters:
      version:
        type: string
        default: "1.3.2"
    steps:
    - run:
        name: Install SBT
        command: |
          curl -L -o sbt-<< parameters.version >>.deb https://dl.bintray.com/sbt/debian/sbt-<< parameters.version >>.deb
          sudo dpkg -i sbt-<< parameters.version >>.deb
          rm sbt-<< parameters.version >>.deb
    - restore_cache:
        key: sbt-cache-2

  save_sbt_cache:
    description: "Save SBT cache"
    steps:
    - save_cache:
        key: sbt-cache-2
        paths:
          - "~/.ivy2/cache"
          - "~/.sbt"
          - "~/.m2"
          - "~/.coursier"

jobs:
  format_checks:
    docker:
    - image: circleci/openjdk:8
    steps:
    - checkout
    - setup_sbt
    - run: sbt scalafmtCheckAll scalafmtSbtCheck || { echo "[error] Code not formatted prior to commit. Run 'sbt scalafmtAll scalafmtSbt' then commit the reformatted code."; false; }




