version: 2.1

commands:
  setup_sbt:
    description: "Set up SBT"
    parameters:
      version:
        type: string
        default: "1.3.3"
    steps:
    - run:
        name: Install SBT
        command: |
          curl -L -o sbt-<< parameters.version >>.deb https://dl.bintray.com/sbt/debian/sbt-<< parameters.version >>.deb
          sudo dpkg -i sbt-<< parameters.version >>.deb
          rm sbt-<< parameters.version >>.deb
    - restore_cache:
        key: sbt-cache-2

  save_sbt_cache:
    description: "Save SBT cache"
    steps:
    - save_cache:
        key: sbt-cache-2
        paths:
          - "~/.ivy2/cache"
          - "~/.sbt"
          - "~/.m2"
          - "~/.coursier"

  setup_npm:
    description: "Set up npm"
    steps:
    - run:
        name: Install nmp
        command: |
          cd node-support
          npm install
          cd ../samples/js-shopping-cart/
          npm install
          cd -


jobs:
  format_checks:
    docker:
    - image: circleci/openjdk:8
    steps:
    - checkout
    - setup_sbt
    - run: sbt scalafmtCheckAll scalafmtSbtCheck || { echo "[error] Code not formatted prior to commit. Run 'sbt scalafmtAll scalafmtSbt' then commit the reformatted code."; false; }
    - save_sbt_cache

  sbt_tests:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - setup_sbt
      - run: sbt test
      - save_sbt_cache

  doc_tests:
    docker:
      - image: ayltai/circleci-openjdk-node:jdk8-node10
    steps:
      - checkout
      - setup_sbt
      - setup_npm
      - run: sbt 'set concurrentRestrictions in Global += Tags.limitAll(1)' docs/paradox docs/test
      - run: cd docs/src/test/js && npm install && cd -
      - run: cd docs/src/test/js && npm test && cd -
      - save_sbt_cache

  minikube_tests:
    orbs:
      minikube: ccpgames/minikube@0.0.1
    steps:
      run: |
        name: Add Operator
        command: >-
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get |
          bash &&
          helm init --wait
          name: Initialize Helm Tiller Service

workflows:
  version: 2

  build:
    jobs:
      - minikube_tests
